import { SettingSchemaDesc } from '@logseq/libs/dist/LSPlugin'
import { AIProvider } from './modules/logseq/types/settings'
import { ChatGroqModelEnum, ClaudeModelEnum, GeminiAIModelEnum, MistralModelEnum, OllamaEmbeddingModelEnum, OllamaModelEnum, OpenAIModelEnum, OpenRouterModelEnum } from './modules/logseq/types/models'

const settings: SettingSchemaDesc[] = [
  {
    key: 'provider',
    type: 'enum',
    title: 'LLM Provider',
    description: 'Choose your preferred provider.',
    default: AIProvider.Gemini,
    enumChoices: [
      AIProvider.Gemini,
      AIProvider.OpenAI,
      AIProvider.Ollama,
      AIProvider.Groq,
      AIProvider.OpenRouter,
      AIProvider.Claude,
      AIProvider.Mistral,
    ]
  },
  {
    key: 'embeddingProvider',
    type: 'enum',
    title: 'LLM Embedding Provider',
    description: 'Choose your preferred embedding provider.',
    default: AIProvider.Gemini,
    enumChoices: [
      AIProvider.Gemini,
      AIProvider.Ollama,
      AIProvider.OpenRouter,
    ]
  },
  {
    key: 'geminiSettings',
    type: 'heading',
    title: 'Gemini Settings',
    description: 'Settings for Gemini provider.',
    default: '',
  },
  {
    key: 'geminiApiKey',
    type: 'string',
    title: 'Gemini API Key',
    description: 'Your Gemini API Key (This key will saved locally). https://ai.google.dev/gemini-api/docs/api-key',
    default: '',
  },
  {
    key: 'geminiModel',
    type: 'enum',
    title: 'Gemini Model',
    description: 'Select Gemini Model. Note: Gemini 2.5 and 2.0 models are recommended. Older models may have limited availability.',
    default: GeminiAIModelEnum.Gemini25Flash,
    enumChoices: [
      GeminiAIModelEnum.Gemini25Pro,
      GeminiAIModelEnum.Gemini25Flash,
      GeminiAIModelEnum.Gemini25FlashPreview,
      GeminiAIModelEnum.Gemini20Flash,
      GeminiAIModelEnum.Gemini20FlashExp,
      GeminiAIModelEnum.Gemini20FlashLite,
    ]
  },
  {
    key: 'openAiSettings',
    type: 'heading',
    title: 'OpenAI Settings',
    description: 'Settings for OpenAI provider.',
    default: '',
  },
  {
    key: 'openAIBasePath',
    type: 'string',
    title: 'OpenAI Base Path',
    description: 'Your custom OpenAI Base Path. For example: https://api.perplexity.ai/',
    default: 'https://api.openai.com/v1/',
  },
  {
    key: 'openAiApiKey',
    type: 'string',
    title: 'OpenAI API Key',
    description: 'Your OpenAI API Key (This key will saved locally). https://platform.openai.com/api-keys',
    default: '',
  },
  {
    key: 'openAiModel',
    type: 'enum',
    title: 'OpenAI Model',
    description: 'Select OpenAI Model',
    default: OpenAIModelEnum.GPT4oMini,
    enumChoices: [
      OpenAIModelEnum.GPT4o,
      OpenAIModelEnum.GPT4oMini,
      OpenAIModelEnum.GPT4Turbo,
      OpenAIModelEnum.GPT4,
      OpenAIModelEnum.GPT3_5Turbo,
      OpenAIModelEnum.O1Preview,
      OpenAIModelEnum.O1Mini,
    ]
  },
  {
    key: 'ollamaSettings',
    type: 'heading',
    title: 'Ollama Settings',
    description: 'Settings for Ollama provider.',
    default: '',
  },
  {
    key: 'ollamaEndpoint',
    type: 'string',
    title: 'Ollama Endpoint',
    description: 'Your local Ollama endpoint (e.g http://localhost:11434)',
    default: 'http://localhost:11434',
  },
  {
    key: 'ollamaModel',
    type: 'enum',
    title: 'Ollama Model',
    description: 'Select Ollama model',
    default: OllamaModelEnum.llama3_3,
    enumChoices: [
      OllamaModelEnum.llama3_3,
      OllamaModelEnum.llama3_2,
      OllamaModelEnum.llama3_1,
      OllamaModelEnum.llama3,
      OllamaModelEnum.gemma2,
      OllamaModelEnum.mistral_nemo,
      OllamaModelEnum.qwen2,
      OllamaModelEnum.deepseek_coder_v2,
      OllamaModelEnum.phi3,
      OllamaModelEnum.mistral,
      OllamaModelEnum.mixtral,
      OllamaModelEnum.codegemma,
      OllamaModelEnum.command_r,
      OllamaModelEnum.command_r_plus,
      OllamaModelEnum.llava,
      OllamaModelEnum.gemma,
      OllamaModelEnum.codellama,
    ],
  },
  {
    key: 'ollamaEmbeddingModel',
    type: 'enum',
    title: 'Ollama Embedding Model',
    description: 'Select Ollama embedding model',
    default: OllamaEmbeddingModelEnum.mxbai_embed_large,
    enumChoices: [
      OllamaEmbeddingModelEnum.mxbai_embed_large,
      OllamaEmbeddingModelEnum.nomic_embed_text,
      OllamaEmbeddingModelEnum.all_minilm,
    ],
  },
  {
    key: 'chatGroqSettings',
    type: 'heading',
    title: 'ChatGroq Settings',
    description: 'Settings for GroqCloud provider.',
    default: '',
  },
  {
    key: 'chatGroqAPIKey',
    type: 'string',
    title: 'Groq API Key',
    description: 'Your Groq API Key (This key will saved locally). https://console.groq.com/keys',
    default: '',
  },
  {
    key: 'chatGroqModel',
    type: 'enum',
    title: 'Groq Model',
    description: 'Select Groq Model',
    default: ChatGroqModelEnum.llama_3_3_70b_versatile,
    enumChoices: [
      ChatGroqModelEnum.llama_3_3_70b_versatile,
      ChatGroqModelEnum.llama_3_1_70b_versatile,
      ChatGroqModelEnum.llama_3_1_8b_instant,
      ChatGroqModelEnum.llama3_70b_8192,
      ChatGroqModelEnum.llama3_8b_8192,
      ChatGroqModelEnum.gemma2_9b_it,
      ChatGroqModelEnum.mixtral_8x7b_32768,
    ]
  },
  {
    key: 'openRouterSettings',
    type: 'heading',
    title: 'OpenRouter Settings',
    description: 'Settings for OpenRouter provider.',
    default: '',
  },
  {
    key: 'openRouterAPIKey',
    type: 'string',
    title: 'OpenRouter API Key',
    description: 'Your OpenRouter API Key (This key will saved locally). https://openrouter.ai/keys',
    default: '',
  },
  {
    key: 'openRouterModel',
    type: 'string',
    title: 'OpenRouter Model',
    description: 'Enter the exact OpenRouter model slug (e.g. openai/gpt-4o, openai/gpt-5.1-chat).',
    default: OpenRouterModelEnum.OpenAIGPT4oMini,
    inputAs: 'textarea',
  },
  {
    key: 'openRouterEmbeddingModel',
    type: 'string',
    title: 'OpenRouter Embedding Model',
    description: 'Enter the embedding model slug from OpenRouter (e.g. google/gemini-embedding-001).',
    default: OpenRouterModelEnum.GoogleGeminiEmbedding001,
    inputAs: 'textarea',
  },
  {
    key: 'claudeSettings',
    type: 'heading',
    title: 'Claude Settings',
    description: 'Settings for Claude (Anthropic) provider.',
    default: '',
  },
  {
    key: 'claudeAPIKey',
    type: 'string',
    title: 'Claude API Key',
    description: 'Your Claude API Key (This key will saved locally). https://console.anthropic.com/settings/keys',
    default: '',
  },
  {
    key: 'claudeModel',
    type: 'enum',
    title: 'Claude Model',
    description: 'Select Claude Model',
    default: ClaudeModelEnum.Claude35Sonnet20241022,
    enumChoices: [
      ClaudeModelEnum.Claude35Sonnet20241022,
      ClaudeModelEnum.Claude35Haiku20241022,
      ClaudeModelEnum.Claude3Opus20240229,
      ClaudeModelEnum.Claude3Haiku20240307,
    ]
  },
  {
    key: 'mistralSettings',
    type: 'heading',
    title: 'Mistral Settings',
    description: 'Settings for Mistral AI provider.',
    default: '',
  },
  {
    key: 'mistralAPIKey',
    type: 'string',
    title: 'Mistral API Key',
    description: 'Your Mistral API Key (This key will saved locally). https://console.mistral.ai/api-keys',
    default: '',
  },
  {
    key: 'mistralModel',
    type: 'enum',
    title: 'Mistral Model',
    description: 'Select Mistral Model',
    default: MistralModelEnum.MistralLarge,
    enumChoices: [
      MistralModelEnum.MistralLarge,
      MistralModelEnum.MistralSmall,
      MistralModelEnum.Codestral,
      MistralModelEnum.Mixtral8x7B,
    ]
  },
  {
    key: 'privacyControl',
    type: 'heading',
    title: 'Privacy Control',
    description: 'These settings will help you to protect your confidential documents.',
    default: '',
  },
  {
    key: 'blacklistedPages',
    type: 'string',
    title: 'Blacklisted Pages',
    description: 'Put page name titles separated in commas. These pages will not be included as a context on any AI Conversations.',
    default: 'a,b,c,todo,card,done,later,doing',
    inputAs: 'textarea',
  },
  {
    key: 'blacklistedKeywords',
    type: 'string',
    title: 'Blacklisted Keywords',
    description: 'Put some keywords, blocks or pages containing these words will not be included as a context on any AI Conversations..',
    default: 'pass,api key,confidential,password',
    inputAs: 'textarea',
  },
  {
    key: 'includeDatePage',
    type: 'boolean',
    title: 'Include Date Page?',
    description: 'Do you want to include date page ([[August 24th, 2024]]) as context to any AI Conversation?',
    default: false,
  },
  {
    key: 'includePageReferences',
    type: 'boolean',
    title: 'Include Page References?',
    description: 'Do you want to include linked and unlinked references to the current page as context?',
    default: true,
  },
  {
    key: 'customSystemPrompt',
    type: 'string',
    title: 'Custom System Prompt',
    description: 'Customize the AI assistant\'s behavior by providing your own system prompt. Leave empty to use the default prompt. Your custom prompt will be prepended to the default instructions.',
    default: '',
    inputAs: 'textarea',
  },
  {
    key: 'keyboardShortcut',
    type: 'string',
    title: 'Keyboard Shortcut',
    description: 'Keyboard shortcut to open AssistSeq. Use format like "mod+shift+a" (mod = Ctrl on Windows/Linux, Cmd on macOS). Requires plugin reload to take effect.',
    default: 'mod+shift+a',
  },
  {
    key: 'maxRecursionDepth',
    type: 'number',
    title: 'Document Relational Depth',
    description: 'How deep is the documents related to the current document will be included.',
    default: 3,
  },
  {
    key: 'maxEmbeddedDocuments',
    type: 'number',
    title: 'Maximum Embedded Documents',
    description: 'Maximum number of documents to be embedded to each prompt.',
    default: 10,
  },
  {
    key: 'includeVisualization',
    type: 'boolean',
    title: 'Include Visualization?',
    description: 'Do you want to include visualization? (AI can draw visualization for you using charts and diagrams)',
    default: true,
  },
  {
    key: 'includeURLScrapper',
    type: 'boolean',
    title: 'Include Visualization?',
    description: 'URL Scrapper is getting rejected by Gemini Provider. Please disable this when using Gemini Provider.',
    default: true,
  },
  {
    key: 'tavilySearch',
    type: 'heading',
    title: 'Tavily Search',
    description: 'Tavily Search API is a search engine optimized for LLMs, aimed at efficient, quick and persistent search results.',
    default: '',
  },
  {
    key: 'includeTavilySearch',
    type: 'boolean',
    title: 'Include Tavily Search?',
    description: 'Do you want to include Tavily Search Engine results?',
    default: true,
  },
  {
    key: 'tavilyAPIKey',
    type: 'string',
    title: 'Tavily API Key',
    description: 'Your Tavily API Key (This key will saved locally). https://app.tavily.com/home ',
    default: '',
  },
]

export default settings
